#pragma checksum "I:\02\NewInternship\Internship.Web\Views\Shared\_Routine2\_DefaultActions.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "fa197ca567e145ac20180b9b83b47f93d7570672"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Shared__Routine2__DefaultActions), @"mvc.1.0.view", @"/Views/Shared/_Routine2/_DefaultActions.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/Shared/_Routine2/_DefaultActions.cshtml", typeof(AspNetCore.Views_Shared__Routine2__DefaultActions))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 1 "I:\02\NewInternship\Internship.Web\Views\_ViewImports.cshtml"
using Internship.Web.Areas.Identity;

#line default
#line hidden
#line 2 "I:\02\NewInternship\Internship.Web\Views\_ViewImports.cshtml"
using Internship.Core.Common.IdentityToolkit;

#line default
#line hidden
#line 3 "I:\02\NewInternship\Internship.Web\Views\_ViewImports.cshtml"
using Internship.Core.Common.PersianToolkit;

#line default
#line hidden
#line 4 "I:\02\NewInternship\Internship.Web\Views\_ViewImports.cshtml"
using Internship.Core.DomainModels.Entity.Identity;

#line default
#line hidden
#line 5 "I:\02\NewInternship\Internship.Web\Views\_ViewImports.cshtml"
using Internship.Core.DomainModels.ViewModel.Identity;

#line default
#line hidden
#line 6 "I:\02\NewInternship\Internship.Web\Views\_ViewImports.cshtml"
using Internship.Core.DomainModels.ViewModel.Identity.Settings;

#line default
#line hidden
#line 7 "I:\02\NewInternship\Internship.Web\Views\_ViewImports.cshtml"
using Microsoft.AspNetCore.Routing;

#line default
#line hidden
#line 8 "I:\02\NewInternship\Internship.Web\Views\_ViewImports.cshtml"
using Microsoft.Extensions.Options;

#line default
#line hidden
#line 9 "I:\02\NewInternship\Internship.Web\Views\_ViewImports.cshtml"
using System.Globalization;

#line default
#line hidden
#line 10 "I:\02\NewInternship\Internship.Web\Views\_ViewImports.cshtml"
using System.Threading.Tasks;

#line default
#line hidden
#line 11 "I:\02\NewInternship\Internship.Web\Views\_ViewImports.cshtml"
using System.Net;

#line default
#line hidden
#line 12 "I:\02\NewInternship\Internship.Web\Views\_ViewImports.cshtml"
using DNTPersianUtils.Core;

#line default
#line hidden
#line 13 "I:\02\NewInternship\Internship.Web\Views\_ViewImports.cshtml"
using Internship.Infrastructure.DataLayer.Context;

#line default
#line hidden
#line 14 "I:\02\NewInternship\Internship.Web\Views\_ViewImports.cshtml"
using Internship.Core.DomainModels.Entity.AuditableEntity;

#line default
#line hidden
#line 1 "I:\02\NewInternship\Internship.Web\Views\Shared\_Routine2\_DefaultActions.cshtml"
using Internship.Core.DomainModels.SSOT;

#line default
#line hidden
#line 2 "I:\02\NewInternship\Internship.Web\Views\Shared\_Routine2\_DefaultActions.cshtml"
using Internship.Core.DomainModels.ViewModel.Routine2;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"fa197ca567e145ac20180b9b83b47f93d7570672", @"/Views/Shared/_Routine2/_DefaultActions.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"51872ae7d6162f128a2b528f6a5dce7432e7ca3d", @"/Views/_ViewImports.cshtml")]
    public class Views_Shared__Routine2__DefaultActions : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<int>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(110, 4, true);
            WriteLiteral("\r\n\r\n");
            EndContext();
            BeginContext(115, 88, false);
#line 6 "I:\02\NewInternship\Internship.Web\Views\Shared\_Routine2\_DefaultActions.cshtml"
Write(Html.Partial("_Routine2/_ChangeStep", new Routine2ChangeStep(Model, Routine2Actions.F1)));

#line default
#line hidden
            EndContext();
            BeginContext(203, 2, true);
            WriteLiteral("\r\n");
            EndContext();
            BeginContext(206, 88, false);
#line 7 "I:\02\NewInternship\Internship.Web\Views\Shared\_Routine2\_DefaultActions.cshtml"
Write(Html.Partial("_Routine2/_ChangeStep", new Routine2ChangeStep(Model, Routine2Actions.F2)));

#line default
#line hidden
            EndContext();
            BeginContext(294, 2, true);
            WriteLiteral("\r\n");
            EndContext();
            BeginContext(297, 88, false);
#line 8 "I:\02\NewInternship\Internship.Web\Views\Shared\_Routine2\_DefaultActions.cshtml"
Write(Html.Partial("_Routine2/_ChangeStep", new Routine2ChangeStep(Model, Routine2Actions.F3)));

#line default
#line hidden
            EndContext();
            BeginContext(385, 2, true);
            WriteLiteral("\r\n");
            EndContext();
            BeginContext(388, 88, false);
#line 9 "I:\02\NewInternship\Internship.Web\Views\Shared\_Routine2\_DefaultActions.cshtml"
Write(Html.Partial("_Routine2/_ChangeStep", new Routine2ChangeStep(Model, Routine2Actions.F4)));

#line default
#line hidden
            EndContext();
            BeginContext(476, 2, true);
            WriteLiteral("\r\n");
            EndContext();
            BeginContext(479, 88, false);
#line 10 "I:\02\NewInternship\Internship.Web\Views\Shared\_Routine2\_DefaultActions.cshtml"
Write(Html.Partial("_Routine2/_ChangeStep", new Routine2ChangeStep(Model, Routine2Actions.F5)));

#line default
#line hidden
            EndContext();
            BeginContext(567, 2, true);
            WriteLiteral("\r\n");
            EndContext();
            BeginContext(570, 88, false);
#line 11 "I:\02\NewInternship\Internship.Web\Views\Shared\_Routine2\_DefaultActions.cshtml"
Write(Html.Partial("_Routine2/_ChangeStep", new Routine2ChangeStep(Model, Routine2Actions.F6)));

#line default
#line hidden
            EndContext();
            BeginContext(658, 2, true);
            WriteLiteral("\r\n");
            EndContext();
            BeginContext(661, 88, false);
#line 12 "I:\02\NewInternship\Internship.Web\Views\Shared\_Routine2\_DefaultActions.cshtml"
Write(Html.Partial("_Routine2/_ChangeStep", new Routine2ChangeStep(Model, Routine2Actions.F7)));

#line default
#line hidden
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<int> Html { get; private set; }
    }
}
#pragma warning restore 1591
