#pragma checksum "I:\02\NewInternship\Internship.Web\Areas\Identity\Views\RolesManager\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "d9820f8fef6becf1c44abf674886bae5075e0baa"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Areas_Identity_Views_RolesManager_Index), @"mvc.1.0.view", @"/Areas/Identity/Views/RolesManager/Index.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Areas/Identity/Views/RolesManager/Index.cshtml", typeof(AspNetCore.Areas_Identity_Views_RolesManager_Index))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 1 "I:\02\NewInternship\Internship.Web\Areas\Identity\Views\_ViewImports.cshtml"
using Internship.Web.Areas.Identity;

#line default
#line hidden
#line 2 "I:\02\NewInternship\Internship.Web\Areas\Identity\Views\_ViewImports.cshtml"
using Internship.Core.Common.IdentityToolkit;

#line default
#line hidden
#line 3 "I:\02\NewInternship\Internship.Web\Areas\Identity\Views\_ViewImports.cshtml"
using Internship.Core.Common.PersianToolkit;

#line default
#line hidden
#line 4 "I:\02\NewInternship\Internship.Web\Areas\Identity\Views\_ViewImports.cshtml"
using Internship.Core.DomainModels.Entity.Identity;

#line default
#line hidden
#line 5 "I:\02\NewInternship\Internship.Web\Areas\Identity\Views\_ViewImports.cshtml"
using Internship.Web.Services.Contracts.Identity;

#line default
#line hidden
#line 6 "I:\02\NewInternship\Internship.Web\Areas\Identity\Views\_ViewImports.cshtml"
using Internship.Web.Services.Contracts;

#line default
#line hidden
#line 7 "I:\02\NewInternship\Internship.Web\Areas\Identity\Views\_ViewImports.cshtml"
using Internship.Core.DomainModels.ViewModel.Identity;

#line default
#line hidden
#line 8 "I:\02\NewInternship\Internship.Web\Areas\Identity\Views\_ViewImports.cshtml"
using Internship.Core.DomainModels.ViewModel.Identity.Emails;

#line default
#line hidden
#line 9 "I:\02\NewInternship\Internship.Web\Areas\Identity\Views\_ViewImports.cshtml"
using Internship.Core.DomainModels.ViewModel.Identity.Settings;

#line default
#line hidden
#line 10 "I:\02\NewInternship\Internship.Web\Areas\Identity\Views\_ViewImports.cshtml"
using Microsoft.AspNetCore.Routing;

#line default
#line hidden
#line 11 "I:\02\NewInternship\Internship.Web\Areas\Identity\Views\_ViewImports.cshtml"
using Microsoft.Extensions.Options;

#line default
#line hidden
#line 12 "I:\02\NewInternship\Internship.Web\Areas\Identity\Views\_ViewImports.cshtml"
using System.Globalization;

#line default
#line hidden
#line 13 "I:\02\NewInternship\Internship.Web\Areas\Identity\Views\_ViewImports.cshtml"
using System.Threading.Tasks;

#line default
#line hidden
#line 14 "I:\02\NewInternship\Internship.Web\Areas\Identity\Views\_ViewImports.cshtml"
using System.Net;

#line default
#line hidden
#line 15 "I:\02\NewInternship\Internship.Web\Areas\Identity\Views\_ViewImports.cshtml"
using DNTPersianUtils.Core;

#line default
#line hidden
#line 16 "I:\02\NewInternship\Internship.Web\Areas\Identity\Views\_ViewImports.cshtml"
using Internship.Infrastructure.Services.Contracts.Identity;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"d9820f8fef6becf1c44abf674886bae5075e0baa", @"/Areas/Identity/Views/RolesManager/Index.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"8855e927cc29baffb9e09864cdbecda77e26a913", @"/Areas/Identity/Views/_ViewImports.cshtml")]
    public class Areas_Identity_Views_RolesManager_Index : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<IEnumerable<RoleAndUsersCountViewModel>>
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("alert alert-warning mt-5"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("card-header"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("name", "_AllRolesList", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_3 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("card-body"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_4 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("card mt-5"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Internship.Web.Areas.Identity.TagHelpers.VisibilityTagHelper __Internship_Web_Areas_Identity_TagHelpers_VisibilityTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_PartialTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(48, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 3 "I:\02\NewInternship\Internship.Web\Areas\Identity\Views\RolesManager\Index.cshtml"
  
    ViewData["Title"] = "مدیریت نقش‌های سیستم";

#line default
#line hidden
            BeginContext(106, 2, true);
            WriteLiteral("\r\n");
            EndContext();
            BeginContext(108, 1481, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("div", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "d9820f8fef6becf1c44abf674886bae5075e0baa7781", async() => {
                BeginContext(146, 1437, true);
                WriteLiteral(@"
    <a href=""#"" class=""close"" data-dismiss=""alert"">×</a>
    <ul>
        <li>
            ویرایش نام نقش‌های ثابت سیستم و یا حذف آن‌ها می‌تواند دسترسی به قسمت‌های از پیش طراحی شده‌ی برنامه را از کار بیندازد
            <span dir=""ltr"">.([Authorize(Roles = ConstantRoles.Admin)])</span>
            بنابراین هرگونه تغییری در اینجا نیاز است در کدهای برنامه نیز منعکس شود و یا برعکس.
        </li>
        <li>
            در اینجا می‌توان به هر نقش ثابت، دسترسی‌های پویایی را نیز اعطاء کرد. در این حالت کنترلر و یا اکشن متدهایی با پالیسی سطوح دسترسی پویا، لیست شده و قابل انتخاب خواهند بود
            <span dir=""ltr"">.([Authorize(Policy = ConstantPolicies.DynamicPermission)])</span>
        </li>
        <li>
            در حالت استفاده‌ی از سطوح دسترسی پویا، با تغییر نام و یا حذف نقش‌های ثابت، نیازی به تغییری در کدهای برنامه نخواهد بود.
        </li>
        <li>تمام کاربران منتسب به نقش Admin، به صفحات دارای سطوح دسترسی پویا نیز دسترسی کاملی دارند و نیازی به افزودن آن‌ها به لیست نفرات این نوع نقش‌ها");
                WriteLiteral(@"ی پویای خاص نیست.</li>
        <li>اگر در یک فیلتر Authorize، نقش جدیدی را بکار گرفته‌اید، می‌توانید آن‌را در اینجا اضافه کنید.</li>
        <li>اگر نام نقش بکار رفته‌ی در فیلترهای Authorize را تغییر داده‌اید، می‌توانید این تغییرات را نیز در اینجا اعمال و ویرایش نمائید.</li>
        <li>اگر از فیلترهای Authorize، نقشی را به طور کامل حذف کرده‌اید، می‌توانید این نقش را در اینجا نیز حذف کنید.</li>
    </ul>
");
                EndContext();
            }
            );
            __Internship_Web_Areas_Identity_TagHelpers_VisibilityTagHelper = CreateTagHelper<global::Internship.Web.Areas.Identity.TagHelpers.VisibilityTagHelper>();
            __tagHelperExecutionContext.Add(__Internship_Web_Areas_Identity_TagHelpers_VisibilityTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(1589, 4, true);
            WriteLiteral("\r\n\r\n");
            EndContext();
            BeginContext(1593, 358, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("div", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "d9820f8fef6becf1c44abf674886bae5075e0baa10548", async() => {
                BeginContext(1616, 6, true);
                WriteLiteral("\r\n    ");
                EndContext();
                BeginContext(1622, 93, false);
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("div", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "d9820f8fef6becf1c44abf674886bae5075e0baa10935", async() => {
                    BeginContext(1647, 33, true);
                    WriteLiteral("\r\n        <h5 class=\"card-title\">");
                    EndContext();
                    BeginContext(1681, 17, false);
#line 31 "I:\02\NewInternship\Internship.Web\Areas\Identity\Views\RolesManager\Index.cshtml"
                          Write(ViewData["Title"]);

#line default
#line hidden
                    EndContext();
                    BeginContext(1698, 11, true);
                    WriteLiteral("</h5>\r\n    ");
                    EndContext();
                }
                );
                __Internship_Web_Areas_Identity_TagHelpers_VisibilityTagHelper = CreateTagHelper<global::Internship.Web.Areas.Identity.TagHelpers.VisibilityTagHelper>();
                __tagHelperExecutionContext.Add(__Internship_Web_Areas_Identity_TagHelpers_VisibilityTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                EndContext();
                BeginContext(1715, 6, true);
                WriteLiteral("\r\n    ");
                EndContext();
                BeginContext(1721, 91, false);
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("div", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "d9820f8fef6becf1c44abf674886bae5075e0baa12741", async() => {
                    BeginContext(1744, 10, true);
                    WriteLiteral("\r\n        ");
                    EndContext();
                    BeginContext(1754, 46, false);
                    __tagHelperExecutionContext = __tagHelperScopeManager.Begin("partial", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "d9820f8fef6becf1c44abf674886bae5075e0baa13153", async() => {
                    }
                    );
                    __Microsoft_AspNetCore_Mvc_TagHelpers_PartialTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper>();
                    __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_PartialTagHelper);
                    __Microsoft_AspNetCore_Mvc_TagHelpers_PartialTagHelper.Name = (string)__tagHelperAttribute_2.Value;
                    __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_2);
#line 34 "I:\02\NewInternship\Internship.Web\Areas\Identity\Views\RolesManager\Index.cshtml"
__Microsoft_AspNetCore_Mvc_TagHelpers_PartialTagHelper.Model = Model;

#line default
#line hidden
                    __tagHelperExecutionContext.AddTagHelperAttribute("model", __Microsoft_AspNetCore_Mvc_TagHelpers_PartialTagHelper.Model, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
                    await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                    if (!__tagHelperExecutionContext.Output.IsContentModified)
                    {
                        await __tagHelperExecutionContext.SetOutputContentAsync();
                    }
                    Write(__tagHelperExecutionContext.Output);
                    __tagHelperExecutionContext = __tagHelperScopeManager.End();
                    EndContext();
                    BeginContext(1800, 6, true);
                    WriteLiteral("\r\n    ");
                    EndContext();
                }
                );
                __Internship_Web_Areas_Identity_TagHelpers_VisibilityTagHelper = CreateTagHelper<global::Internship.Web.Areas.Identity.TagHelpers.VisibilityTagHelper>();
                __tagHelperExecutionContext.Add(__Internship_Web_Areas_Identity_TagHelpers_VisibilityTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_3);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                EndContext();
                BeginContext(1812, 133, true);
                WriteLiteral("\r\n    <footer class=\"card-footer\">\r\n        <a class=\"btn btn-success\" href=\"#\" id=\"btnCreate\">ایجاد یک نقش جدید</a>\r\n    </footer>\r\n");
                EndContext();
            }
            );
            __Internship_Web_Areas_Identity_TagHelpers_VisibilityTagHelper = CreateTagHelper<global::Internship.Web.Areas.Identity.TagHelpers.VisibilityTagHelper>();
            __tagHelperExecutionContext.Add(__Internship_Web_Areas_Identity_TagHelpers_VisibilityTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_4);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(1951, 4, true);
            WriteLiteral("\r\n\r\n");
            EndContext();
            DefineSection("Scripts", async() => {
                BeginContext(1974, 267, true);
                WriteLiteral(@"
    <script type=""text/javascript"">
        $(function () {
            $('#btnCreate').click(function (e) {
                e.preventDefault(); //می‌خواهیم لینک به صورت معمول عمل نکند

                $.bootstrapModalAjaxForm({
                    postUrl: '");
                EndContext();
                BeginContext(2242, 37, false);
#line 49 "I:\02\NewInternship\Internship.Web\Areas\Identity\Views\RolesManager\Index.cshtml"
                         Write(Url.Action("AddRole", "RolesManager"));

#line default
#line hidden
                EndContext();
                BeginContext(2279, 52, true);
                WriteLiteral("\',\r\n                    renderModalPartialViewUrl: \'");
                EndContext();
                BeginContext(2332, 40, false);
#line 50 "I:\02\NewInternship\Internship.Web\Areas\Identity\Views\RolesManager\Index.cshtml"
                                           Write(Url.Action("RenderRole", "RolesManager"));

#line default
#line hidden
                EndContext();
                BeginContext(2372, 681, true);
                WriteLiteral(@"',
                    renderModalPartialViewData: {},
                    loginUrl: '/identity/login',
                    beforePostHandler: function () {
                    },
                    completeHandler: function () {
                        location.reload();
                    },
                    errorHandler: function () {
                    }
                });
            });

            $(""a[id^='btnEdit']"").click(function (e) {
                e.preventDefault(); //می‌خواهیم لینک به صورت معمول عمل نکند
                var roleId = $(this).data(""edit-id"");

                $.bootstrapModalAjaxForm({
                    postUrl: '");
                EndContext();
                BeginContext(3054, 38, false);
#line 68 "I:\02\NewInternship\Internship.Web\Areas\Identity\Views\RolesManager\Index.cshtml"
                         Write(Url.Action("EditRole", "RolesManager"));

#line default
#line hidden
                EndContext();
                BeginContext(3092, 52, true);
                WriteLiteral("\',\r\n                    renderModalPartialViewUrl: \'");
                EndContext();
                BeginContext(3145, 40, false);
#line 69 "I:\02\NewInternship\Internship.Web\Areas\Identity\Views\RolesManager\Index.cshtml"
                                           Write(Url.Action("RenderRole", "RolesManager"));

#line default
#line hidden
                EndContext();
                BeginContext(3185, 715, true);
                WriteLiteral(@"',
                    renderModalPartialViewData: JSON.stringify({ ""id"": roleId }),
                    loginUrl: '/identity/login',
                    beforePostHandler: function () {
                    },
                    completeHandler: function () {
                        location.reload();
                    },
                    errorHandler: function () {
                    }
                });
            });

            $(""a[id^='btnDelete']"").click(function (e) {
                e.preventDefault(); //می‌خواهیم لینک به صورت معمول عمل نکند
                var roleId = $(this).data(""delete-id"");

                $.bootstrapModalAjaxForm({
                    postUrl: '");
                EndContext();
                BeginContext(3901, 36, false);
#line 87 "I:\02\NewInternship\Internship.Web\Areas\Identity\Views\RolesManager\Index.cshtml"
                         Write(Url.Action("Delete", "RolesManager"));

#line default
#line hidden
                EndContext();
                BeginContext(3937, 52, true);
                WriteLiteral("\',\r\n                    renderModalPartialViewUrl: \'");
                EndContext();
                BeginContext(3990, 46, false);
#line 88 "I:\02\NewInternship\Internship.Web\Areas\Identity\Views\RolesManager\Index.cshtml"
                                           Write(Url.Action("RenderDeleteRole", "RolesManager"));

#line default
#line hidden
                EndContext();
                BeginContext(4036, 473, true);
                WriteLiteral(@"',
                    renderModalPartialViewData: JSON.stringify({ ""id"": roleId }),
                    loginUrl: '/identity/login',
                    beforePostHandler: function () {
                    },
                    completeHandler: function () {
                        location.reload();
                    },
                    errorHandler: function () {
                    }
                });
            });
        });
    </script>
");
                EndContext();
            }
            );
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<IEnumerable<RoleAndUsersCountViewModel>> Html { get; private set; }
    }
}
#pragma warning restore 1591
